### ISSUE TITLE
Exception on load

### ISSUE THREAD

**Issue by uniquelau** [TailBlazor/HeroIcons#1]
Running .NET 5.0, Blazor PWA
Installed in client project and updated _Import.
Referencing the component directly
SVG is requested by browser.
However, exception is thrown.

![image](https://user-images.githubusercontent.com/914735/113415788-dcf0d100-93b7-11eb-86d0-96772a15bdef.png)

**Throw Exception at TailBlazor.HeroIcons.TailBlazorHeroIconBase.OnInitialized()**

```Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at TailBlazor.HeroIcons.TailBlazorHeroIconBase.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

SVG requested 3 times (as expected)
![image](https://user-images.githubusercontent.com/914735/113416248-cdbe5300-93b8-11eb-894e-b663317e42f7.png)

**Comment by TaylorWatson** [comment]
looks related to this.

[PlatformNotSupportedException on Blazor Client Side](https://github.com/OData/odata.net/issues/1784)

I will take a look to see if I can work around WASM's limitations.

**Comment by DanteDeRuwe** [comment]
Any updates on this?

**Comment by badHax** [comment]
This seems to be related to a thread blocking call in [TailBlazorHeroIcon.razor.cs](https://github.com/TailBlazor/HeroIcons/blob/0c017af89ff40dadd43132e4e1819d6ed33a549d/src/TailBlazor.HeroIcons/TailBlazorHeroIcon.razor.cs#L42) which is definitely not supported in Blazor.
```C#
 var document = await Task.Run(() => {
                    return XDocument.Load($"{baseUri}_content/TailBlazor.HeroIcons/icons/{EnumExtension.GetEnumDescription(IconStyle)}/{EnumExtension.GetEnumDescription(Icon)}.svg");
            });
```

One workaround that I have found is to override this class and load the SVG through an HTTP request and use async method to load it instead:
```C#
       //.....
       // Use non blocking HTTP request to stream the SVG
        var client = new HttpClient();
        var icon = (await client.GetAsync(NavigationManager.BaseUri + "_content/TailBlazor.HeroIcons/icons/" +
                                          IconStyle.GetEnumDescription() + "/" + Icon.GetEnumDescription() + ".svg"))
            .Content;
        await using var stream = await icon.ReadAsStreamAsync();

        // load asynchronously
        var root = (await XDocument.LoadAsync(stream, LoadOptions.PreserveWhitespace, CancellationToken.None)).Root;

        root?.SetAttributeValue("width", Width);
        root?.SetAttributeValue("height", Height);
        root?.SetAttributeValue("stroke", "");
        root?.SetAttributeValue("class", _classStroke);
        foreach (var xelement in root?.Descendants().Select((Func<XElement, XElement>)(path => path)) ??
                                 new List<XElement>())
        {
            if (xelement.Attribute("stroke-width") != null)
                xelement.SetAttributeValue("stroke-width", StrokeWidth);
            if (xelement.Attribute("fill") != null)
                xelement.SetAttributeValue("fill", StrokeWidth);
        }

        _svgIcon = root?.ToString();
    //...
```
Then I created a CustomHeroIcons.cs
```C#
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace Custom.Components.HeroIcons
{
    public class CustomHeroIcon : CustomHeroIconBase
    {
        protected override void BuildRenderTree(RenderTreeBuilder __builder)
        {
            if (this.EnableComments)
                __builder.AddContent(0, this._svgIconComment);
            __builder.AddContent(1, (MarkupString)this._svgIcon);
        }
    }
}

```

Finally, I just use this in my code:
```HTML
        <button @onclick="NavigateToHome">
          Home
          <CustomHeroIcon Class="tw-h-6 tw-w-6"
                              Icon="HeroIcon.Home"></CustomHeroIcon>
        </button>
```

**Comment by TaylorWatson** [comment]
Thanks, if you want submit a PR or I'll update using this method instead
